### ISSUE TITLE
Best way to setup routes for rendering Cell::Rails cells

### ISSUE THREAD

**Issue by mckenziec** [trailblazer/cells#119]
There is a related issue on this topic, but it doesn't address what the best practice or supported way to render a Cell::Rails cell class from routes.rb. Using Cell::Base cell class objects from routes works fine but not with Devise. If you're trying to use the Devise methods from a Cell::Base.render_cell_for initiated Cell, you'll find that the ActionController attributes are missing. e.g. like request, env, etc... This is mainly a problem if you use Devise, which wants to simply call "request" (e.g. request.env["get something"] when doing something like getting the current_user.

This works, but not with Devise methods since things like request are missing. Maybe there's a method for passing the request into render_cell_for in a way that will allow Devise to pick it up naturally.  

```
class ActivityCell < Cell::Base
  def display(opts = {})
    puts current_user
  end

match "/dashboard/widget/:name" => proc { |env|
  cell_name = env["action_dispatch.request.path_parameters"][:name]
  [ 200, {}, [ Cell::Base.render_cell_for(cell_name, :display) ]]
}
```

Basically I get: NameError (undefined local variable or method `request' for #ActivityCell:0x5f51970):

If I switch to Cell::Rails:

```
class ActivityCell < Cell::Rails
  def display(opts = {})
    puts current_user
  end

match "/dashboard/widget/:name" => proc { |env|
  cell_name = env["action_dispatch.request.path_parameters"][:name]
  [ 200, {}, [ Cell::Base.render_cell_for(cell_name, :display) ]]
}
```

I get a different, familiar error: ArgumentError (wrong number of arguments (0 for 1)):

I then tried something different:

```
include Cells::Rails::ActionController
...
match "/dashboard/widget/:name" => proc { |env|
  cell_name = env["action_dispatch.request.path_parameters"][:name]
  [ 200, {}, [ render_cell(cell_name, :display) ]]
}
```

Right number of arguments, but request is still not available: NoMethodError (undefined method `request' for #ActionDispatch::Routing::Mapper:0x4c93c38)

If it's possible to instantiate Cell::Rails in the route and pass it to the render method, can someone give an example? Thank you.

**Comment by kikorb** [comment]
Hi,

I think doing this
```ruby
match "/dashboard/widget/:name" => proc { |env|
  cell_name = env["action_dispatch.request.path_parameters"][:name]
  request = ActionDispatch::Request.new(env)
  [ 200, {}, [ Cell::Rack.render_cell_for(cell_name, :display, request) ]]
}
```
No longer works since the third param is actually expecting a controller and not a request object (In fact you can get undefined method request for request object)

The solution I found is to do this:
```ruby
match "/posts" => proc { |env|
  controller = ActionController::Base.new
  controller.request = ActionDispatch::Request.new(env)

  [ 200, {}, [ Cell::Rack.render_cell_for(:post, :show, controller, controller.request.query_parameters) ]]
}
```
