### ISSUE TITLE
Is it good style to use external helpers, for example Devise's current_user or user_signed_in?

### ISSUE THREAD

**Issue by jmuheim** [trailblazer/cells#193]
I copied some code from a former partial into a new cell. The code uses some helpers from [Devise](https://github.com/plataformatec/devise):

``` ruby
# layouts/application.html.haml
= render_cell :mini_hub, :show
```

``` slim
# cells/mini_hub/show.html.haml
- if user_signed_in?
  p Welcome, #{current_user.username}!
```

Cells complained that it doesn't know these helpers, so I added them specifically:

``` ruby
class MiniHubCell < Cell::Rails
  include Devise::Controllers::Helpers
  helper_method :current_user, :user_signed_in?

  def show
    render
  end

end
```

**1st question:**

Why do I have to explicitly call `helper_method`? Shouldn't just all helpers be available without it? In my case, they weren't.

**2nd question:**

Is it good style to use external helpers within cells? Doesn't this mean there are more dependencies between the cells and the surrounding code?

**3rd question:**

If it is good style, how can I make those dependencies available in specs? I'm getting the following error now when running specs:

```
  1) MiniHubCell cell rendering rendering show 
     Failure/Error: subject { render_cell :mini_hub, :show }
     ActionView::Template::Error:
       undefined method `authenticate' for nil:NilClass
     # ./app/cells/mini_hub/show.html.slim:1:in `_app_cells_mini_hub_show_html_slim__919887079305921142_70205468343840'
     # ./app/cells/mini_hub_cell.rb:6:in `show'
     # ./spec/cells/mini_hub_cell_spec.rb:13:in `block (4 levels) in <top (required)>'
     # ./spec/cells/mini_hub_cell_spec.rb:15:in `block (4 levels) in <top (required)>'
```

I think it has something to do with missing some Devise dependencies.

**4th question:**

If it is not good style, should I rewrite my code to something like this?

``` ruby
# layouts/application.html.haml
= render_cell :mini_hub, :show, member: current_member
```

``` slim
# cells/mini_hub/show.html.haml
- if member.present?
  p Welcome, #{member.username}!
```

If so, why do I get a `wrong number of arguments (1 for 0)` error now for `render_cell`?

Thanks a lot for help. I'm just diving into cells and it's very promising, but I'm struggling a bit. :wink:

**Comment by crokobit** [comment]
GREAT!
