### ISSUE TITLE
[Question] calling `cache` method for a "state" will overwrite settings in previous call?

### ISSUE THREAD

**Issue by PikachuEXE** [trailblazer/cells#351]
I got something like this in a concept cell:

``` ruby
cache(
      :show,
      :cache_key,
      expires_in: 1.hour,
      if: :should_be_cached_hourly,
    )
    cache(
      :show,
      :cache_key,
      expires_in: 1.day,
      if: :should_be_cached_daily,
    )
    cache(
      :show,
      :cache_key,
      expires_in: 1.month,
      if: :should_be_cached_monthly,
    )
```

I want to cache the the cell hourly / daily / monthly based on a model attribute value (which is a time)
But it seems the caching occurs when `should_be_cached_monthly` is `true`
This is discovered by caching spec not failing when the method name for cache key is wrong

**Comment by apotonick** [comment]
I am pretty sure you can call `cache` only once, or when multiple times, the last one wins. We could think about making the options dynamic, e.g. `->(options) { expires_in: logic_to_find_out }`.
