### ISSUE TITLE
Pass block to cell from Rails template not working

### ISSUE THREAD

**Issue by lukeredpath** [trailblazer/cells#406]
New user of cells here, I'm trying to see if I can use it to DRY up a bunch of reusable components from a Bootstrap theme I'm working with.

As well as application specific views, I'm trying to write some generic reusable components. I'm not sure what the best approach is for this but as a starting point I'm trying to use blocks and the new `yield` feature but it doesn't seem to be working as I'd hoped.

Given a cell:

``` ruby
class PageBodyCell < Cell::ViewModel
end
```

And it's template:

``` haml
.row
  .col-lg-12
    .wrapper.wrapper-content
      = yield if block_given?

```

When I call it in my Rails view like this:

``` erb
<%= cell(:page_body) do %>
  Some Content
<% end %>
```

Then the block does not get passed to the cell. If I pass the block to call instead:

``` erb
<%= cell(:page_body).() do %>
  Some Content
<% end %>
```

The block does get passed, but the contents of the block are rendered twice. Once before the actual cell and once within the cell.

What's the right approach here?

**Comment by apotonick** [comment]
Passing blocks from views doesn't really work because of the way the horrible output buffer is implemented. I'd use nested cells instead of this.

We will work on a new technique to allow this kind of code, but it will take a while. Sorry!

**Comment by MichaelBurge** [comment]
I ran into this, and this new default 'show' implementation seems to work around it:

`class ApplicationCell < Cell::ViewModel
  include ActionView::Helpers::CaptureHelper
  def show(&block)
    render do
      capture(&block)
    end
  end
end
`

**Comment by pdfrod** [comment]
I also have the need for something like this. Creating nested cells would not be feasible to me, as I'd quickly have hundreds on mini cells.

Is there any solution in the works for this? Or is there another recommended approach?

**Comment by apotonick** [comment]
Are you talking about rendering cells in cells (that we can make work), or rendering cells in controller views?

**Comment by pdfrod** [comment]
In my case, it's rendering cells in controller views.

**Comment by apotonick** [comment]
See this comment: https://github.com/trailblazer/cells/issues/406#issuecomment-221709226

This will never work, because the compiled controller view code is not compatible with the compiled code in Cells. They use a magic output buffer instance variable, we use a simple data flow. Sorry!

**Comment by apotonick** [comment]
@pdfrod Can you make a pseudo code example of the view rendering the cell, with the block? Maybe we can find another way.

**Comment by pdfrod** [comment]
@apotonick So here's an example of where this has come up: I have an UI accordion element that I want to implement as a cell. An accordion can have multiple items, so an accordion item would be modeled as an AccordionItemCell. The AccordionItemCell renders something like this:

```
<li>
  <div class="title"><%= title %></div>
  <div class="content"><%= content %></div>
</li>
```

I would like to be able to use it like this:

```
<%= cell(:accordion_item, title: 'Item 1') do %>
  Content 1
<%= end %>

<%= cell(:accordion_item, title: 'Item 2') do %>
  Content 2
<%= end %>

....

<%= cell(:accordion_item, title: 'Item N') do %>
  Content N
<%= end %>
```

Since accordion item's content can be arbitrarily complex, I want to pass a block instead of a simple argument. Do you see a better approach to do this?

**Comment by apotonick** [comment]
Of course there's a ~better~ different approach! :grimacing: Define an object that models the accordion's content. An array would do.

```ruby
titles = [ "Overview", "API" ]
```

Then, use the `collection:` option when rendering the cells.

```ruby
cell( Accordion::Cell::Item, collection: titles )
```

What you are trying to do with the block actually makes managing the accordion harder.

**Comment by pdfrod** [comment]
I'm not sure how that would work when each accordion item can have content as arbitrary as in the following example:

```HTML
<form>
  <ul class="accordion">
    <li class="accordion-item">
      <div class="title">...</div>
      <div class="content">
        <input ...>
        Blah blah
        <select>...</select>
      </div>
    </li>

    <li class="accordion-item">
      <div class="title">...</div>
      <div class="content">
        Hello
        <input ..>
      </div>
    </li>

    <li class="accordion-item">
      <div class="title">...</div>
      <div class="content">
        <img ...>
        <input ..>
      </div>
    </li>
  </ul>
</form>
```

In general, there isn't a common pattern between the items that I can easily extract into a single object. By your suggestion, it seems that for this example I would have to write 3 additional objects (one for each item content) or am I missing something?

**Comment by apotonick** [comment]
Hm, you could also write a dedicated cell that manages that according fragment (that's your controller view now). You could then use the built-in capture and pass that into the cell as an option?

**Comment by pdfrod** [comment]
Yeah that works, but I was hoping the Cell's library would already offer a more elegant/simple solution for this use case, since there are a lot of situations where I need something like this. Anyway, thanks for your help!

**Comment by apotonick** [comment]
It's difficult, since all template engines have a different way of capturing (which happens in the block you want), and some are a bit hacky where the captured block isn't eval'ed where it should be, and so on. Are you using ERBse?

**Comment by apotonick** [comment]
BTW, in Rails views, this only works because they have one global view instance for all fragments. The fact that capturing works solely relies on the contract that all tpl engines write to `@output_buffer`, which is, again, global state, and leads to many problems once you split up your views into smaller objects. That's probably the reason ActionView will never have real components. :cry:

**Comment by pdfrod** [comment]
Actually I'm not using ERB, I'm using Slim. Not sure if that makes any difference.

Yeah, that's why I'm trying to move away from Rails views as much as possible - there's too much global state and functions going around, it's hard to build modularized and reusable components.

**Comment by apotonick** [comment]
With Slim, it should work fine if you use `capture`.

**Comment by pdfrod** [comment]
Cool, I'll try that. Thanks!
