### ISSUE TITLE
Allow using cells with latest stable HAML release (4.0.7)

### ISSUE THREAD

**Issue by phillipoertel** [trailblazer/cells#435]
Hi Nick,

my current client would like to start using cells; parts of the UI logic are complex, so it's a perfect use case for it.

They use the latest stable HAML release, 4.0.7. Unfortunately cells only works with HAML 4.1, which had it's stable release [pending for three years](https://rubygems.org/gems/haml/versions/4.1.0.alpha.2), and may never have one (they [wanted to release 5.0 beta](https://github.com/haml/haml/issues/856) more than a year ago but haven't). I wonder what's going on; has everyone switched to hamlit or slim?
Since the Rails application is large, it's out of scope to switch to hamlit any time soon; we'd have to retest the whole application (we have no experience with feature differences / compatibility of haml and hamlit). Same goes for using a maybe maintained / stable 4.1 beta HAML version.

So, would there be any way to get cells to work with HAML 4.0.x? Maybe we can provide a PR if you point us to the spot(s) that need to be adapted.

**Comment by phillipoertel** [comment]
I just realized the following: cells works fine with 4.0.7, only cells' documentation is not up to date. 

The README says "Make sure to bundle Haml 4.1: `gem "haml", github: "haml/haml", ref: "7c7c169"`" Their commit `7c7c169` (2015-06-08) is older than and also contained in the 4.0.7 (`99cf4e`, 2015-08-10) release: https://github.com/haml/haml/commits/master.

**Comment by apotonick** [comment]
Closing this as we can't do anything about the Haml releases. I recommend using Slim.
