### ISSUE TITLE
undefined method `cell'

### ISSUE THREAD

**Issue by TheFlow0360** [trailblazer/cells#454]
I'm creating an engine as a gem that contains a cell. When searching for this error I just found that the answer always was a missing gem: either `cells-rails` or `cells-erb`. But I have this in my gemspec:

    spec.add_dependency "rails", "~> 5.1"
    spec.add_dependency "cells", "~> 4.1"
    spec.add_dependency "cells-rails", "~> 0.0"
    spec.add_dependency "cells-erb", "~> 0.1"

I still can't call the `cell` helper iny the dummy application, though (in the tests it's working). Do I need to require cells somewhere in the files where I use my custom cell or what am I doing wrong?

**Comment by apotonick** [comment]
Since the `cells-rails` dependency comes via a gem itself, you might have to `require "cells/rails"` in the dummy app or - maybe better - in your engine's lib file (`yourgem/lib/yourgem.rb`).

**Comment by TheFlow0360** [comment]
I put it in the lib file and it worked, thanks a lot!
