### ISSUE TITLE
Can't use cell from engine in rails application

### ISSUE THREAD

**Issue by TheFlow0360** [trailblazer/cells#455]
I created an engine containing a cell (you can find it [here](https://github.com/TheFlow0360/criteria_operator-ui_component)). I added the gem for the engine to my application's gemfile and mounted the routes:

    # gemfile
    gem 'criteria_operator' # dependency for the engine
    gem 'cells' # i added these three because `bundler list` didn't show me `cells-rails` and `cells-erb` even though they are listed as dependencies for the engine
    gem 'cells-rails'
    gem 'cells-erb'
    gem 'criteria_operator-ui_component' # the engine
    
    ...
    
    # routes.rb
    mount CriteriaOperator::UiComponent::Engine => '/criteria_operator-ui_component'

After trying around I managed to find out that I need `include Cell::RailsExtensions::ActionController` if I want to use the `cells` helper. However, I'm still not able to use my cell because the constant is not initialized (`ActionView::Template::Error (uninitialized constant CriteriaOperator::UiComponent::CriteriaEditor)`).

I tested the cell in my dummy app, it was working fine there. I guess the dummy somehow directly loads the classes from the engine instead of using the gem. But even if it's this way, as far as I know, I'm not allowed to require classes outside of the `lib` folder in my engine's lib file, so I wouldn't know what to change. 

What am I doing wrong? Does my engine need to do additional work to provide the application with the classes, or do I need to change something in the application? I'm completly stuck... I'm not very familiar with ruby and rails and don't have a clue on how to proceed now...

**Comment by TheFlow0360** [comment]
also see [this question on SO](https://stackoverflow.com/questions/44966087/cant-use-cells-from-an-engine-inside-rails-application#) for more details. Haven't gotten an answer there, either...

**Comment by apotonick** [comment]
I don't know if autoloading works with a Rails engine, I am guessing you have to `require_relative` the files you need. The error indicates that files defining class constants haven't been loaded. This is usually done manually in gems.

**Comment by apotonick** [comment]
Here's a typical "top-level" gem file: https://github.com/trailblazer/trailblazer/blob/master/lib/trailblazer.rb

**Comment by TheFlow0360** [comment]
Do you mean I have to user `require_relative` in the gem or in the application?

**Comment by apotonick** [comment]
In the gem! See the above link as an example, the trailblazer gem loads all files with the classes it wants to provide to the user. :beers:

**Comment by TheFlow0360** [comment]
Ok, thanks, I'll try that out as soon as I can. Also, feel free to create an answer on SO since there is still an open bounty (at least for the next few hours).

**Comment by TheFlow0360** [comment]
Ok, that basically works, at least the constants are now known. Still, I can't include the javascript and ccs like this, right?  But I need the javascript and css to be applied correctly, which isn't the case now...

I somehow get the feeling the way cells works is not really compatible with how Engines are intended to work. Adding these `require_relative`s is already discouraged, since the files are outside of the `lib` folder...

**Comment by apotonick** [comment]
Why are your engine cell files outside of `lib`? You should have a bunch of lines in your `my-rails-engine.rb` file saying stuff such as

```ruby
require_relative "cell/bla/main.rb" # will load my-rails-engine/lib/cell/bla/main.rb
```

This is a standard thing to do in gems, you will find it in a hundred thousands of them. Maybe the engine is not aware of the load path where your gem's cells sit, and you need to add it to the engine's configuration. Rails engines are a great idea, but the implementation is quite limited to Rails-only files (e.g. models).

@rafaelfranca can you help us? We want to have cell class files from a Rails engine autoloaded by Rails - is that what engines are supposed to do automatically?

**Comment by apotonick** [comment]
@TheFlow0360 Komm mal auf https://gitter.im/trailblazer/chat !

**Comment by rafaelfranca** [comment]
engines only autoload files inside app. I see that the cells are inside `lib` so the automatic autoload will not work. You can make it work too, but you will need to add `lib/cell` to `config.eager_load_paths`.

**Comment by TheFlow0360** [comment]
@rafaelfranca the auto-loading for the cells now does work, my current problems are the assets... my css and js is not getting applied

**Comment by TheFlow0360** [comment]
@rafaelfranca the auto-loading for the cells now does work, my current problems are the assets... my css and js is not getting applied

**Comment by TheFlow0360** [comment]
The issue was realted to ACtiveADmin overriding the assets...
