### ISSUE TITLE
replace declarative-option with trailblazer-option

### ISSUE THREAD

**Issue by rocket-turtle** [trailblazer/cells#511]
Currently declarative-option and trailblazer-option get installed.

There was already a merge for this: https://github.com/trailblazer/cells/pull/492/files
But I think the changes got lost with the force push in https://github.com/trailblazer/cells/pull/509 https://github.com/trailblazer/cells/compare/b5ceeaaa295cdc2094003679148e996fb52b6c73..573c411daa00ed41293824123b839949660b5daf

Was that intentional? Do you plan to replace declarative-option?

---

cells [4.1.8](https://rubygems.org/gems/cells/versions/4.1.8)
- updated to [declarative-builder](https://rubygems.org/gems/declarative-builder) ~> 0.2.0
  - which changed from [declarative-option](https://rubygems.org/gems/declarative-option) < 0.2.0 to [trailblazer-option](https://rubygems.org/gems/trailblazer-option) ~> 0.1.0
  - https://github.com/apotonick/declarative-builder/commit/097c11f75311191ca3654ce24e688ca73f1dba02
- cells still depends on [declarative-option](https://rubygems.org/gems/declarative-option) < 0.2.0

**Comment by AlfonsoUceda** [comment]
Hey @rocket-turtle sorry for the problem!

I created this PR, cold you check it? https://github.com/trailblazer/cells/pull/512

**Comment by rocket-turtle** [comment]
Thank you. Looks good to me. I get no error with our codebase.
