### ISSUE TITLE
Calling cached cell writes nothing to log file

### ISSUE THREAD

**Issue by jamesbebbington** [trailblazer/cells#64]
I'm not sure if this is by design or not but I was expecting that when caching is configured for a cell, that details of cache hits, misses and deletions would be written to the log file (at least in development).

Is this something that is broken, intentionally missing or just as yet, not implemented and would be accepted as a patch?

**Comment by schorsch** [comment]
Do i need to wire the notifications to the log output myself? As the cache output is pretty usefull for a dev.

**Comment by schorsch** [comment]
... yes i finally medi it to try cells

**Comment by apotonick** [comment]
@schorsch Yo! Good to see you here!

@timoschilling Hilft!

**Comment by timoschilling** [comment]
@schorsch 
Here is a subscribe example for `read_fragment.action_controller` and `write_fragment.action_controller`
```ruby
ActiveSupport::Notifications.subscribe('read_fragment.action_controller') do |name, start, finish, id, payload|
  name    # => String, name of the event (such as 'read_fragment.action_controller' from above)
  start   # => Time, when the instrumented block started execution
  finish  # => Time, when the instrumented block ended execution
  id      # => String, unique ID for this notification
  payload # => Hash, the payload
end
```

**Comment by timoschilling** [comment]
@schorsch contact me if you need more support
